[project]
name = "mazeplayground"
version = "0.1.0"
description = "MazePlayground â€” ein kleines Maze-Generator- und Solver-Projekt"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["rich"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
